name: package ci flow

on: push

jobs:
  test-and-lint:
    name: Test & Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install deps
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_ACTIONS }}
      - name: Lint
        run: npm run lint

  publish:
    name: Publish package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: test-and-lint
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com
          scope: '@geiserman'
      - name: Publishing package
        run: npm ci && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_ACTIONS }}

  publish-alpha:
    name: Publish alpha to registry
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'chore(): alpha')"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@geiserman'
      - name: Patching package.json to have commit hash as an alpha version
        run: jq '.version = .version + "-alpha.${{github.sha}}"' package.json > tmp.json && mv tmp.json package.json
      - name: Publishing alpha package
        run: npm ci && npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_ACTIONS }}


